[[repositories]]
username= "Ankur Srivastava"
email = "myuser@xmail.com"
giturl = "github.com"
[[repositories]]
username= "Ankur Srivastava"
email = "myuserfor-github@xmail.com"
giturl = "gitlab.com"
