name: Linux

on:
  push:
  pull_request:
  schedule:
    - cron: "0 7 * * *"

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        version:
          - stable
          - nightly

    name: ${{ matrix.version }} - x86_64-unknown-linux-gnu
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install ${{ matrix.version }}
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.version }}-x86_64-unknown-linux-gnu

      - uses: Swatinem/rust-cache@v1

      - name: Run tests
        uses: actions-rs/cargo@v1
        timeout-minutes: 40
        with:
          command: test
          args: --all --all-features --no-fail-fast -- --nocapture

      - name: Install tarpaulin
        continue-on-error: true
        run: |
          cargo install cargo-tarpaulin

      - name: Generate coverage report
        continue-on-error: true
        run: |
          cargo tarpaulin --out Xml --all --all-features
